# Image Matching Challenge 2025 - Model Configuration
# This file contains performance-related parameters only

#------------------------------------------------------------------------------
# Model Architecture Configuration
#------------------------------------------------------------------------------
model:
  # Available types: dino, loftr, superglue, advanced
  type: advanced

  # Feature dimension for embedding space
  feature_dim: 12288

  # Backbone architecture (used with 'advanced' model type)
  # Options: resnet50, efficientnet_b3, vit_b_16, dinov2
  backbone: dinov2

  num_layers: 24
  multi_scale: true
  attention_heads: 16

#------------------------------------------------------------------------------
# Training Parameters
#------------------------------------------------------------------------------
training:
  # Batch size - controls memory usage and training stability
  # Note: Values < 2 may cause BatchNorm issues
  batch_size: 6

  # Number of complete passes through the training dataset
  epochs: 100

  # Base learning rate for optimization
  learning_rate: 5.0e-5

  # Weight decay regularization factor
  weight_decay: 5.0e-5

  # Optimizer selection
  # Options: adam, adamw, sgd
  optimizer: adamw

  # Warmup epochs for learning rate scheduler
  warmup_epochs: 10

  # Minimum learning rate (for cosine annealing)
  min_learning_rate: 1.0e-7

  # Random seed for reproducibility
  seed: 42

  # Prevent OOM maximizing GPU usage
  gradient_accumulation_steps: 2
  gradient_clip_val: 1.0
  sync_batchnorm: true

#------------------------------------------------------------------------------
# Loss Function Configuration
#------------------------------------------------------------------------------
loss:
  # Primary loss function type
  # Options: combined, enhanced, metric_learning
  type: enhanced

  # Weight for similarity loss component
  similarity_weight: 1.5

  # Weight for pose estimation loss component
  pose_weight: 0.5

  # Margin for contrastive loss
  contrastive_margin: 1.0

  # Temperature parameter for contrastive losses
  # Controls the sharpness of similarity distribution
  temperature: 0.07

  # Weight for rotation component in pose loss
  rotation_weight: 1.0

  # Weight for translation component in pose loss
  translation_weight: 1.0

  # Use adaptive weights based on loss values
  use_adaptive_weights: true

  # Use focal loss for similarity prediction
  use_focal_loss: true

#------------------------------------------------------------------------------
# Advanced Training Options
#------------------------------------------------------------------------------
advanced:
  # Use mixed precision training (FP16)
  # Speeds up training with minimal accuracy impact
  use_mixed_precision: true
  precision: 'bf16'

  # Use Exponential Moving Average of model weights
  # Improves stability and generalization
  use_ema: true

  # EMA decay rate (higher = slower updating)
  # Recommended range: 0.99 to 0.9999
  ema_decay: 0.9999

  # Early stopping patience (epochs without improvement)
  early_stopping_patience: 10

  # Checkpoint saving frequency (epochs)
  save_every_n_epochs: 5
  activation_checkpointing: true

  # Safety device for preventing OOM
  gradient_checkpointing: true
  cudnn_benchmark: true
  torch_compile: true
  deterministic: false